from flask_wtf import FlaskForm
from wtforms import Form, SubmitField, StringField, IntegerField, FormField
from wtforms.validators import DataRequired, Optional
from wtforms.fields.html5 import DateField, DateTimeField


class SearchForm(FlaskForm) :
    date = DateField('Sort Date')
    part = StringField('Part')
    job = StringField('Job')
    submit = SubmitField('Submit')

class EditForm(FlaskForm) :
    Employee = StringField('Employee', [DataRequired()])
    StartTime = DateTimeField('Start Time (Year-Month-Day Hours:Min:Sec)', [DataRequired()])
    EndTime = DateTimeField('End Time (Year-Month-Day Hours:Min:Sec)')
    TableNumber = IntegerField('Table #', [DataRequired()])
    Part = IntegerField('Part', [DataRequired()])
    Job = IntegerField('Job #', [DataRequired()])
    GoodQuantity = IntegerField('Good Quantity', validators=[Optional(strip_whitespace=True)])
    Assembly = IntegerField('Assembly', validators=[Optional(strip_whitespace=True)])
    AutoSort = IntegerField('AutoSort', validators=[Optional(strip_whitespace=True)])
    BadThreads = IntegerField('Bad Threads', validators=[Optional(strip_whitespace=True)])
    Bent = IntegerField('Bent', validators=[Optional(strip_whitespace=True)])
    Blisters = IntegerField('Blisters', validators=[Optional(strip_whitespace=True)])
    BrokenCore = IntegerField('Broken Core', validators=[Optional(strip_whitespace=True)])
    Buffing = IntegerField('Buffing', validators=[Optional(strip_whitespace=True)])
    Contamination = IntegerField('Contamination', validators=[Optional(strip_whitespace=True)])
    DamagedDie = IntegerField('Damaged Die', validators=[Optional(strip_whitespace=True)])
    Debris = IntegerField('Debris', validators=[Optional(strip_whitespace=True)])
    Dimensional = IntegerField('Dimensional', validators=[Optional(strip_whitespace=True)])
    Flash = IntegerField('Flash', validators=[Optional(strip_whitespace=True)])
    GateVestige = IntegerField('Gate Vestige', validators=[Optional(strip_whitespace=True)])
    HeatSinks = IntegerField('Heat Sinks', validators=[Optional(strip_whitespace=True)])
    EjectorPinLength = IntegerField('Ejector Pin Length', validators=[Optional(strip_whitespace=True)])
    Lamination = IntegerField('Lamination', validators=[Optional(strip_whitespace=True)])
    LeakTest = IntegerField('LeakTest', validators=[Optional(strip_whitespace=True)])
    MixedParts = IntegerField('Mixed Parts', validators=[Optional(strip_whitespace=True)])
    Other = IntegerField('Other', validators=[Optional(strip_whitespace=True)])
    PartDamage = IntegerField('Part Damage', validators=[Optional(strip_whitespace=True)])
    PartsNotTapped = IntegerField('Parts Not Tapped', validators=[Optional(strip_whitespace=True)])
    PartsOnGates = IntegerField('Parts On Gates', validators=[Optional(strip_whitespace=True)])
    Plating = IntegerField('Plating', validators=[Optional(strip_whitespace=True)])
    PoorFill = IntegerField('Poor Fill', validators=[Optional(strip_whitespace=True)])
    Porosity = IntegerField('Porosity', validators=[Optional(strip_whitespace=True)])
    Skiving = IntegerField('Skiving', validators=[Optional(strip_whitespace=True)])
    Soldering = IntegerField('Soldering', validators=[Optional(strip_whitespace=True)])
    StartUp = IntegerField('Start Up', validators=[Optional(strip_whitespace=True)])
    SurfaceFinish = IntegerField('Surface Finish', validators=[Optional(strip_whitespace=True)])
    TrimDamage = IntegerField('Trim Damage', validators=[Optional(strip_whitespace=True)])
    Weight = IntegerField('Weight', validators=[Optional(strip_whitespace=True)])
    WrongPart = IntegerField('Wrong Part', validators=[Optional(strip_whitespace=True)])
    submit = SubmitField('Submit', validators=[Optional(strip_whitespace=True)])

class NewScrap(FlaskForm) :
    scrap_reason = StringField('New Scrap Reason')
    submit = SubmitField('Submit')

class EditScrap(FlaskForm) :
    Assembly = IntegerField('Assembly')
    AutoSort = IntegerField('AutoSort')
    BadThreads = IntegerField('BadThreads')
    Bent = IntegerField('Bent')
    Blisters = IntegerField('Blisters')
    BrokenCore = IntegerField('BrokenCore')
    Buffing = IntegerField('Buffing')
    Contamination = IntegerField('Contamination')
    DamagedDie = IntegerField('DamagedDie')
    Debris = IntegerField('Debris')
    Dimensional = IntegerField('Dimensional')
    Flash = IntegerField('Flash')
    GateVestige = IntegerField('GateVestige')
    HeatSinks = IntegerField('HeatSinks')
    EjectorPinLength = IntegerField('EjectorPinLength')
    Lamination = IntegerField('Lamination')
    LeakTest = IntegerField('LeakTest')
    MixedParts = IntegerField('MixedParts')
    Other = IntegerField('Other')
    PartDamage = IntegerField('PartDamage')
    PartsNotTapped = IntegerField('PartsNotTapped')
    PartsOnGates = IntegerField('PartsOnGates')
    Plating = IntegerField('Plating')
    PoorFill = IntegerField('PoorFill')
    Porosity = IntegerField('Porosity')
    Skiving = IntegerField('Skiving')
    Soldering = IntegerField('Soldering')
    StartUp = IntegerField('StartUp')
    SurfaceFinish = IntegerField('SurfaceFinish')
    TrimDamage = IntegerField('TrimDamage')
    Weight = IntegerField('Weight')
    WrongPart = IntegerField('WrongPart')
    scrap_submit = SubmitField('Submit')

class BigEdit(FlaskForm) :
    basic_info = FormField(EditForm)
    scrap_info = FormField(EditScrap)